# Generated by Django 6.0.6 on 2026-06-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='is_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
